export const Base = [
    {
      id: "1",
      region:"North africa",
      country: "Morocco",
      city: "Marrakech",
      starts: "4",
      hotel:"AKKA Alinda",
      price:"150 $",
      img: "https://wallpapercave.com/w/wp5229572.jpg",  
    },
    {
        id: "2",
        region:"North africa",
        country: "Morocco",
        city: "Tanger",
        starts: "5",
        hotel:"El Continental",
        price:"220 $",
        img: "https://wallpapercave.com/w/wp3394546.jpg",  
    },
    {
        id: "3",
        region:"North africa",
        country: "Tunisia",
        city: "Djerba",
        starts: "5",
        hotel:"Movenpick",
        price:"230 $",
        img: "https://wallpapercave.com/w/wp2030662.jpg",  
    },
    {
        id: "4",
        region:"North africa",
        country: "Tunisia",
        city: "Tunis",
        starts: "3",
        hotel:"Amzer",
        price:"100 $",
        img: "https://wallpapercave.com/w/wp2030665.jpg",  
    },
    {
        id: "5",
        region:"North africa",
        country: "Tunisia",
        city: "Monastir",
        starts: "4",
        hotel:"Crispo",
        price:"180 $",
        img: "https://wallpapercave.com/w/wp2030734.jpg",  
    },
    {
        id: "6",
        region:"North africa",
        country: "Egypt",
        city: "Alexandria",
        starts: "4",
        hotel:"Al Kasbah",
        price:"180 $",
        img: "https://wallpapercave.com/w/wp11896399.jpg",  
    },
    {
        id: "7",
        region:"Europe",
        country: "Spain",
        city: "Valencia",
        starts: "4",
        hotel:"El Bernabeu",
        price:"180 $",
        img: "https://wallpapercave.com/w/wp1846084.jpg",  
    },
    {
        id: "8",
        region:"Europe",
        country: "Spain",
        city: "Mallorca",
        starts: "5",
        hotel:"Prestana CR7",
        price:"250 $",
        img: "https://wallpapercave.com/w/wp12082234.jpg",  
    },
    {
        id: "9",
        region:"Europe",
        country: "Spain",
        city: "Madrid",
        starts: "5",
        hotel:"Hotel El Rey",
        price:"275 $",
        img: "https://wallpapercave.com/w/wp12082228.jpg",  
    },
    {
        id: "10",
        region:"Europe",
        country: "France",
        city: "Paris",
        starts: "4",
        hotel:"Le Lavoisier",
        price:"150 $",
        img: "https://wallpapercave.com/w/wp12082228.jpg",  
    },
    

];
