export const Base = [
    {
      id: "1",
      region:"North africa",
      country: "Morocco",
      city: "Marrakech",
      stars: "4",
      hotel:"AKKA Alinda",
      price:"150 $",
      img: "https://wallpapercave.com/w/wp5229572.jpg",  
    },
    {
        id: "11",
        region:"Europe",
        country: "France",
        city: "Marseille",
        stars: "5",
        hotel:"La Chapelle",
        price:"300 $",
        img: "https://wallpapercave.com/w/wp10535401.jpg",  
    },
    {
        id: "2",
        region:"North africa",
        country: "Morocco",
        city: "Tanger",
        stars: "5",
        hotel:"El Continental",
        price:"220 $",
        img: "https://wallpapercave.com/w/wp3394546.jpg",  
    },
    {
        id: "3",
        region:"North africa",
        country: "Tunisia",
        city: "Djerba",
        stars: "5",
        hotel:"Movenpick",
        price:"230 $",
        img: "https://wallpapercave.com/w/wp2030662.jpg",  
    },
    {
        id: "4",
        region:"North africa",
        country: "Tunisia",
        city: "Tunis",
        stars: "3",
        hotel:"Amzer",
        price:"100 $",
        img: "https://wallpapercave.com/w/wp2030665.jpg",  
    },
    {
        id: "5",
        region:"North africa",
        country: "Tunisia",
        city: "Monastir",
        stars: "4",
        hotel:"Crispo",
        price:"180 $",
        img: "https://wallpapercave.com/w/wp2030734.jpg",  
    },
    {
        id: "6",
        region:"North africa",
        country: "Egypt",
        city: "Alexandria",
        stars: "4",
        hotel:"Al Kasbah",
        price:"180 $",
        img: "https://wallpapercave.com/w/wp11896399.jpg",  
    },
    {
        id: "7",
        region:"Europe",
        country: "Spain",
        city: "Valencia",
        stars: "4",
        hotel:"El Bernabeu",
        price:"180 $",
        img: "https://wallpapercave.com/w/wp1846084.jpg",  
    },
    {
        id: "8",
        region:"Europe",
        country: "Spain",
        city: "Mallorca",
        stars: "5",
        hotel:"Prestana CR7",
        price:"250 $",
        img: "https://wallpapercave.com/w/wp12082234.jpg",  
    },
    {
        id: "9",
        region:"Europe",
        country: "Spain",
        city: "Madrid",
        stars: "5",
        hotel:"Hotel El Rey",
        price:"275 $",
        img: "https://wallpapercave.com/w/wp12082228.jpg",  
    },
    {
        id: "10",
        region:"Europe",
        country: "France",
        city: "Paris",
        stars: "4",
        hotel:"Le Lavoisier",
        price:"150 $",
        img: "https://wallpapercave.com/w/wp10535399.jpg",  
    },
    
    {
        id: "12",
        region:"Europe",
        country: "France",
        city: "Nancy",
        stars: "4",
        hotel:"Le Capitole",
        price:"245 $",
        img: "https://wallpapercave.com/w/wp10535406.jpg",  
    },
    {
        id: "13",
        region:"Europe",
        country: "Italy",
        city: "Venise",
        stars: "5",
        hotel:"El Bonnuci",
        price:"285 $",
        img: "https://wallpapercave.com/w/wp8725790.jpg",  
    },
    {
        id: "14",
        region:"Europe",
        country: "Italy",
        city: "Torino",
        stars: "5",
        hotel:"Frederico Chiesa",
        price:"300 $",
        img: "https://wallpapercave.com/w/wp10535412.jpg",  
    },
    {
        id: "15",
        region:"Asia",
        country: "Thailand",
        city: "Bangkok",
        stars: "5",
        hotel:"Nishikori Hotel",
        price:"290$",
        img: "https://wallpapercave.com/w/wp12040449.jpg",  
    },
    {
        id: "16",
        region:"Asia",
        country: "Japan",
        city: "Tokyo",
        stars: "5",
        hotel:"Kagawa resort",
        price:"350$",
        img: "https://wallpapercave.com/w/wp12487176.jpg",  
    },



];
